name: taskedin_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.4
  flutter_svg: ^2.0.17
  jwt_decoder: ^2.0.1
  equatable: ^2.0.7
  iconly: ^1.0.1
  file_picker: ^8.0.0
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.4
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.0
  table_calendar: ^3.0.9
  timeline_tile: ^2.0.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/images/logo.png"

  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.jpg"
  adaptive_icon_background: "#FFFFFF"

  adaptive_icon_foreground_inset: 24
  ios_content_padding: 50
  android_content_padding: 50

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
